import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/Providers/ThemeProvidder";
import ToasterPrivder from "@/components/Providers/ToasterPrivder";
import ConfettiProvider from "@/components/Providers/ConfettiProvider";
import { SpeedInsights } from "@vercel/speed-insights/react";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Punzila Digital Learning Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={roboto.className}>
          <ConfettiProvider />
          <ThemeProvider
            attribute='class'
            defaultTheme='root'
            disableTransitionOnChange
          >
            {children}
            <Analytics />
            <SpeedInsights />
            <ToasterPrivder />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
